# Generated by Django 4.2.4 on 2023-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
